name: agent_intentions
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - seaborn=0.12.2
  
  - pip:
      - anthropic==0.20.0
      - llamaapi==0.1.36
      - openai==1.6.1
      - huggingface-hub==0.21.4


